export const FETCH_FAV_RECIPES__BEGIN = 'favourite/FETCH_FAV_RECIPES__BEGIN'
export const FETCH_SHOPPING_LIST__BEGIN = 'favourite/FETCH_SHOPPING_LIS__BEGIN'
export const FETCH_FAV_RECIPES__SUCCES = 'favourite/FETCH_FAV_RECIPES__SUCCESS'
export const FETCH_SHOPPING_LIST__SUCCES = 'favourite/FETCH_SHOPPING_LIST__SUCCESS'